-- Insider Signal Trader — D1 schema

CREATE TABLE IF NOT EXISTS signals (
  id               INTEGER PRIMARY KEY AUTOINCREMENT,
  ticker           TEXT    NOT NULL,
  insider_name     TEXT    NOT NULL,
  insider_role     TEXT    NOT NULL,
  transaction_date TEXT    NOT NULL,
  transaction_value REAL   NOT NULL,
  score            INTEGER NOT NULL,
  raw_filing       TEXT    NOT NULL,
  created_at       DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS recommendations (
  -- UUID generated by crypto.randomUUID() — used in approval deep-links so IDs are unguessable
  id                TEXT    PRIMARY KEY,
  ticker            TEXT    NOT NULL,
  action            TEXT    NOT NULL CHECK(action IN ('BUY', 'SELL', 'HOLD')),
  reasoning         TEXT    NOT NULL,
  signal_id         INTEGER NOT NULL REFERENCES signals(id),
  status            TEXT    NOT NULL DEFAULT 'PENDING'
                    CHECK(status IN ('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', 'EXECUTED')),
  notional          REAL    NOT NULL,
  stop_price        REAL,
  take_profit_price REAL,
  created_at        DATETIME DEFAULT CURRENT_TIMESTAMP,
  resolved_at       DATETIME
);

CREATE TABLE IF NOT EXISTS positions (
  id                 INTEGER PRIMARY KEY AUTOINCREMENT,
  ticker             TEXT    NOT NULL,
  side               TEXT    NOT NULL CHECK(side IN ('long', 'short')),
  qty                REAL    NOT NULL,
  price              REAL    NOT NULL,
  notional           REAL    NOT NULL,
  alpaca_order_id    TEXT    NOT NULL,
  recommendation_id  TEXT    NOT NULL REFERENCES recommendations(id),
  executed_at        DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for common query patterns
CREATE INDEX IF NOT EXISTS idx_signals_ticker       ON signals(ticker);
CREATE INDEX IF NOT EXISTS idx_signals_created_at   ON signals(created_at);
CREATE INDEX IF NOT EXISTS idx_recommendations_status ON recommendations(status);
CREATE INDEX IF NOT EXISTS idx_positions_ticker     ON positions(ticker);
