// Shared domain types used across agents, tools, and routes.

/** Raw SEC Form 4 filing parsed from EDGAR */
export interface Filing {
  ticker: string;
  insiderName: string;
  insiderRole: string;
  transactionDate: string;
  transactionType: "P" | "S" | "A" | "D";
  transactionValue: number;
  sharesTraded: number;
  pricePerShare: number;
  rawXml: string;
}

/** A filing that has been scored by the scoring tool */
export interface ScoredSignal {
  filing: Filing;
  score: number;
  /** Numeric factors for programmatic use / DB storage. */
  scoreBreakdown: {
    roleFactor: number;
    valueFactor: number;
    clusterBonus: number;
    recencyFactor: number;
  };
  /** Human-readable one-liner, e.g. "role(CEO)=+40 | value($1.5M)=+20 | cluster=+20 | recency=+10 | total=90" */
  breakdownSummary: string;
  signalId?: number;
}

/** A trade recommendation produced by the decision agent */
export interface Recommendation {
  /** UUID generated by insertRecommendation(); used in approval deep-links. */
  id?: string;
  ticker: string;
  action: "BUY" | "SELL" | "HOLD";
  reasoning: string;
  /** References signals.id (INTEGER AUTOINCREMENT). Populated via ScoredSignal.signalId. */
  signalId: number;
  status: "PENDING" | "APPROVED" | "REJECTED" | "EXPIRED" | "EXECUTED";
  notional: number;
  /** Bracket order stop-loss price suggested by the LLM. */
  stopPrice?: number;
  /** Bracket order take-profit limit price suggested by the LLM. */
  takeProfitPrice?: number;
  createdAt?: string;
  resolvedAt?: string;
}

/** Live position returned from Alpaca Markets */
export interface AlpacaPosition {
  symbol: string;
  qty: string;
  side: "long" | "short";
  market_value: string;
  avg_entry_price: string;
  unrealized_pl: string;
  unrealized_plpc: string;
}

/** Order object returned from Alpaca Markets after submission */
export interface AlpacaOrder {
  id: string;
  client_order_id: string;
  symbol: string;
  side: "buy" | "sell";
  type: string;
  /** null on notional orders until fill; null on qty orders when notional is set */
  qty: string | null;
  notional: string | null;
  status: string;
  filled_avg_price: string | null;
  filled_qty: string | null;
  created_at: string;
}

/**
 * A held position enriched with the original thesis from D1.
 * Returned by getPositionsWithThesis() — joins positions → recommendations → signals.
 * Used by the DecisionAgent to evaluate whether each trade's original rationale
 * still holds before deciding to sell.
 */
export interface PositionWithThesis {
  ticker: string;
  qty: number;
  entryPrice: number;
  notional: number;
  executedAt: string;
  recommendationId: string;
  /** The full reasoning text Claude wrote when it recommended the BUY. */
  originalReasoning: string;
  /** The insider who triggered the signal. */
  insiderName: string;
  insiderRole: string;
  /** Dollar value of the insider's transaction. */
  signalValue: number;
  /** Score assigned by scoreSignals(). */
  signalScore: number;
  /** Bracket order stop-loss price set at time of recommendation. */
  stopPrice?: number;
  /** Bracket order take-profit limit price set at time of recommendation. */
  takeProfitPrice?: number;
}

/** Audit log entry written to D1 after order execution */
export interface TradeLog {
  id?: number;
  ticker: string;
  side: "long" | "short";
  qty: number;
  price: number;
  notional: number;
  alpacaOrderId: string;
  /** UUID FK → recommendations.id */
  recommendationId: string;
  executedAt?: string;
}

/** Cloudflare Worker environment bindings */
export interface Env {
  DB: D1Database;
  FORM_SCANNER: DurableObjectNamespace;
  DECISION: DurableObjectNamespace;

  // Secrets (from .dev.vars / Workers Secrets)
  ALPACA_API_KEY: string;
  ALPACA_SECRET_KEY: string;
  ANTHROPIC_API_KEY: string;
  TELEGRAM_BOT_TOKEN: string;
  TELEGRAM_CHAT_ID: string;

  // Vars (from wrangler.toml [vars])
  ALPACA_BASE_URL: string;
  ALPACA_DATA_URL: string;
  POSITION_SIZE_USD: string;
  MIN_SIGNAL_SCORE: string;
  APPROVAL_EXPIRY_HOURS: string;
  APPROVAL_BASE_URL: string;
}
